'use strict';
/* Downloads the typefaces from Google Fonts into assets/fonts/ and writes
   assets/css/fonts.css. Run only to change or update a family.

     node tools/fetch-fonts.js

   latin-ext is kept because it carries the Hungarian ő and ű. */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const FONT_DIR = path.join(ROOT, 'assets', 'fonts');
const OUT_CSS = path.join(ROOT, 'assets', 'css', 'fonts.css');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36';
const KEEP = new Set(['latin', 'latin-ext']);

const FAMILIES = [
  {
    name: 'Fraunces',
    file: 'fraunces',
    url: 'https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,400..700,0..100,0..1;1,9..144,400..700,0..100,0..1&display=swap',
  },
  {
    name: 'Familjen Grotesk',
    file: 'familjen-grotesk',
    url: 'https://fonts.googleapis.com/css2?family=Familjen+Grotesk:ital,wght@0,400..700;1,400..700&display=swap',
  },
];

/* @font-face blocks, tagged with the subset comment that precedes each */
function parseFaces(css) {
  const faces = [];
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g;
  let m;
  while ((m = re.exec(css))) {
    const [, subset, body] = m;
    const get = key => (body.match(new RegExp(key + ':\\s*([^;]+);')) || [])[1]?.trim();
    const src = (body.match(/url\((https:[^)]+)\)/) || [])[1];
    faces.push({ subset, src, style: get('font-style') || 'normal', weight: get('font-weight') || '400', range: get('unicode-range') });
  }
  return faces;
}

async function main() {
  fs.mkdirSync(FONT_DIR, { recursive: true });
  const out = ['/* Generated by tools/fetch-fonts.js. Do not edit. */', ''];

  for (const fam of FAMILIES) {
    const res = await fetch(fam.url, { headers: { 'User-Agent': UA } });
    if (!res.ok) throw new Error(`${fam.name}: ${res.status} ${res.statusText}`);
    const faces = parseFaces(await res.text()).filter(f => KEEP.has(f.subset));
    if (!faces.length) throw new Error(`${fam.name}: no latin faces found`);

    for (const f of faces) {
      const base = `${fam.file}-${f.style}-${f.subset}.woff2`;
      const bin = Buffer.from(await (await fetch(f.src, { headers: { 'User-Agent': UA } })).arrayBuffer());
      fs.writeFileSync(path.join(FONT_DIR, base), bin);
      out.push(
        '@font-face {',
        `  font-family: "${fam.name}";`,
        `  font-style: ${f.style};`,
        `  font-weight: ${f.weight};`,
        '  font-display: swap;',
        `  src: url("../fonts/${base}") format("woff2");`,
        `  unicode-range: ${f.range};`,
        '}',
        ''
      );
      console.log(`${base}  ${(bin.length / 1024).toFixed(1)} KB`);
    }
  }

  fs.writeFileSync(OUT_CSS, out.join('\n'));
  console.log(`\nwrote ${path.relative(ROOT, OUT_CSS)}`);
}

main().catch(e => { console.error(e.message); process.exit(1); });
